### ISSUE TITLE
SyntaxError: Unexpected token 'export'

### ISSUE THREAD

**Issue by maan-maker** [wingify/vwo-amplitude-integration#2]
There appears to be an issue with the way the VWOAmplitudePlugin function is being exported in the index.js file. 

First of all, we have to change the import from:
```
import { VWOAmplitudePlugin } from 'vwo-amplitude-integration';
```

To the below since there is no named export:
```
import VWOAmplitudePlugin from 'vwo-amplitude-integration';
```

Secondly, we encounter this error when running our build (using NextJs 13):
```
export default VWOAmplitudePlugin
^^^^^^
SyntaxError: Unexpected token 'export'"
```

Changing the export line inside the index.js file from `export default VWOAmplitudePlugin` to `module.exports = { VWOAmplitudePlugin }` appears to solve the issue.

Can you please review the export method used? Let me know if more info is needed.

**Comment by softvar** [comment]
@artistictechie @prathamesh-88 Please check

**Comment by maan-maker** [comment]
@softvar any update on this issue please? Thanks

**Comment by maan-maker** [comment]
@artistictechie  @softvar  thanks - can we get a release out for this please? Cheers

**Comment by softvar** [comment]
@maan-maker it's released on npm. The latest version is v1.1.0
